/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as CourseIndexImport } from './routes/course/index'
import { Route as PostsPostIdImport } from './routes/posts/$postId'
import { Route as PlanPlanPageImport } from './routes/plan/PlanPage'
import { Route as CourseCourseIdImport } from './routes/course/$courseId'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as SignSignupImport } from './routes/Sign/Signup'
import { Route as SignSigninImport } from './routes/Sign/Signin'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const CourseIndexRoute = CourseIndexImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

const PlanPlanPageRoute = PlanPlanPageImport.update({
  id: '/plan/PlanPage',
  path: '/plan/PlanPage',
  getParentRoute: () => rootRoute,
} as any)

const CourseCourseIdRoute = CourseCourseIdImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const SignSignupRoute = SignSignupImport.update({
  id: '/Sign/Signup',
  path: '/Sign/Signup',
  getParentRoute: () => rootRoute,
} as any)

const SignSigninRoute = SignSigninImport.update({
  id: '/Sign/Signin',
  path: '/Sign/Signin',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/Sign/Signin': {
      id: '/Sign/Signin'
      path: '/Sign/Signin'
      fullPath: '/Sign/Signin'
      preLoaderRoute: typeof SignSigninImport
      parentRoute: typeof rootRoute
    }
    '/Sign/Signup': {
      id: '/Sign/Signup'
      path: '/Sign/Signup'
      fullPath: '/Sign/Signup'
      preLoaderRoute: typeof SignSignupImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdImport
      parentRoute: typeof rootRoute
    }
    '/plan/PlanPage': {
      id: '/plan/PlanPage'
      path: '/plan/PlanPage'
      fullPath: '/plan/PlanPage'
      preLoaderRoute: typeof PlanPlanPageImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/Sign/Signin': typeof SignSigninRoute
  '/Sign/Signup': typeof SignSignupRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/plan/PlanPage': typeof PlanPlanPageRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/course': typeof CourseIndexRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/Sign/Signin': typeof SignSigninRoute
  '/Sign/Signup': typeof SignSignupRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/plan/PlanPage': typeof PlanPlanPageRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/course': typeof CourseIndexRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/Sign/Signin': typeof SignSigninRoute
  '/Sign/Signup': typeof SignSignupRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/plan/PlanPage': typeof PlanPlanPageRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/course/': typeof CourseIndexRoute
  '/posts/': typeof PostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/Sign/Signin'
    | '/Sign/Signup'
    | '/auth/login'
    | '/auth/register'
    | '/course/$courseId'
    | '/plan/PlanPage'
    | '/posts/$postId'
    | '/course'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/Sign/Signin'
    | '/Sign/Signup'
    | '/auth/login'
    | '/auth/register'
    | '/course/$courseId'
    | '/plan/PlanPage'
    | '/posts/$postId'
    | '/course'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/Sign/Signin'
    | '/Sign/Signup'
    | '/auth/login'
    | '/auth/register'
    | '/course/$courseId'
    | '/plan/PlanPage'
    | '/posts/$postId'
    | '/course/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  SignSigninRoute: typeof SignSigninRoute
  SignSignupRoute: typeof SignSignupRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  PlanPlanPageRoute: typeof PlanPlanPageRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  CourseIndexRoute: typeof CourseIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  SignSigninRoute: SignSigninRoute,
  SignSignupRoute: SignSignupRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  PlanPlanPageRoute: PlanPlanPageRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  CourseIndexRoute: CourseIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/Sign/Signin",
        "/Sign/Signup",
        "/auth/login",
        "/auth/register",
        "/course/$courseId",
        "/plan/PlanPage",
        "/posts/$postId",
        "/course/",
        "/posts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/Sign/Signin": {
      "filePath": "Sign/Signin.tsx"
    },
    "/Sign/Signup": {
      "filePath": "Sign/Signup.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/course/$courseId": {
      "filePath": "course/$courseId.tsx"
    },
    "/plan/PlanPage": {
      "filePath": "plan/PlanPage.tsx"
    },
    "/posts/$postId": {
      "filePath": "posts/$postId.tsx"
    },
    "/course/": {
      "filePath": "course/index.tsx"
    },
    "/posts/": {
      "filePath": "posts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
